apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    # Which pods should be managed by this service
    app: second-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
