apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      # targetPort - the container internal port in which it expect incoming
      # requests.
      targetPort: 80
