apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      # targetPort - the container internal port in which it expect incoming
      # requests.
      targetPort: 8000
