apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      # targetPort - the container internal port in which it expect incoming
      # requests.
      targetPort: 8080
